# Generated by Django 5.2 on 2025-05-28 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_profitdistribution_alter_customuser_role_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('обзвонен', 'Обзвонен'), ('не обзвонен', 'Не обзвонен')], default='не обзвонен', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='kassa',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='curator_percent',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='master_percent',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='operator_percent',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
