# Generated by Django 5.2 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_companybalance_contact_order_transferred_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('master', 'Мастер'), ('operator', 'Оператор'), ('warrant-master', 'Гарантийный мастер'), ('super-admin', 'Супер админ'), ('curator', 'Куратор')], default='master', max_length=20),
        ),
    ]
