# Generated by Django 5.2 on 2025-05-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0005_update_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dist',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
