# Generated by Django 5.2 on 2025-05-31 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0006_customuser_dist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteWorkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1_avg_order_threshold', models.DecimalField(decimal_places=2, default=65000, max_digits=10)),
                ('level1_hours_visible', models.PositiveSmallIntegerField(default=4)),
                ('level2_daily_order_threshold', models.DecimalField(decimal_places=2, default=350000, max_digits=10)),
                ('level2_ten_days_threshold', models.DecimalField(decimal_places=2, default=1500000, max_digits=10)),
                ('level2_hours_visible', models.PositiveSmallIntegerField(default=24)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remote Work Settings',
                'verbose_name_plural': 'Remote Work Settings',
            },
        ),
    ]
