# Generated by Django 5.2 on 2025-05-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0007_remoteworksettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dist',
        ),
        migrations.DeleteModel(
            name='RemoteWorkSettings',
        ),
    ]
