# Generated by Django 5.2 on 2025-05-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0008_remove_customuser_dist_delete_remoteworksettings'),
    ]

    operations = [
    ]
