# Generated by Django 5.2 on 2025-06-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0009_auto_20250531_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dist',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
