# Generated by Django 5.2 on 2025-06-01 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0010_customuser_dist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_check_threshold', models.DecimalField(decimal_places=2, default=65000, help_text='Пороговое значение среднего чека для обычной дистанционки', max_digits=12)),
                ('visible_period_standard', models.PositiveIntegerField(default=28, help_text='Количество часов видимости для обычной дистанционки')),
                ('daily_order_sum_threshold', models.DecimalField(decimal_places=2, default=350000, help_text='Пороговое значение суммы заказов в сутки для суточной дистанционки', max_digits=12)),
                ('net_turnover_threshold', models.DecimalField(decimal_places=2, default=1500000, help_text='Пороговое значение чистого вала за 10 дней для суточной дистанционки', max_digits=12)),
                ('visible_period_daily', models.PositiveIntegerField(default=48, help_text='Количество часов видимости для суточной дистанционки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'super-admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки дистанционки',
                'verbose_name_plural': 'Настройки дистанционки',
            },
        ),
    ]
