# Generated by Django 5.2 on 2025-06-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0011_distancesettingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='distance_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
