# Generated by Django 5.2 on 2025-06-02 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0013_orderlog_transactionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['start'], 'verbose_name': 'Календарное событие', 'verbose_name_plural': 'Календарные события'},
        ),
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='master',
            field=models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('master_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('master_advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kassa_amount_stage1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('master_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('master_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curator_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_kassa_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_stage1_completed', models.BooleanField(default=True)),
                ('is_stage2_completed', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('stage2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_curator', models.ForeignKey(blank=True, limit_choices_to={'role': 'curator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distribution', to='api1.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitDistributionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_percent', models.PositiveIntegerField(default=30, help_text='Аванс мастеру (% от чистой прибыли)')),
                ('initial_kassa_percent', models.PositiveIntegerField(default=70, help_text='Сумма для передачи в кассу (% от чистой прибыли)')),
                ('cash_percent', models.PositiveIntegerField(default=30, help_text='Наличные мастеру сразу (% от общей суммы)')),
                ('balance_percent', models.PositiveIntegerField(default=30, help_text='Зачисление на баланс мастеру (% от общей суммы)')),
                ('curator_percent', models.PositiveIntegerField(default=5, help_text='Зарплата куратору (% от общей суммы)')),
                ('final_kassa_percent', models.PositiveIntegerField(default=35, help_text='Касса компании (% от общей суммы)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super-admin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки распределения прибыли',
                'verbose_name_plural': 'Настройки распределения прибыли',
            },
        ),
    ]
