# Generated by Django 5.2 on 2025-06-02 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0015_extend_balancelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdistributionsettings',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactionlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='action',
            field=models.CharField(default='legacy', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction_type',
            field=models.CharField(choices=[('balance_top_up', 'Пополнение баланса'), ('balance_deduct', 'Списание с баланса'), ('paid_amount_top_up', 'Пополнение выплаченной суммы'), ('paid_amount_deduct', 'Списание с выплаченной суммы'), ('profit_distribution', 'Распределение прибыли'), ('master_payment', 'Выплата мастеру'), ('curator_salary', 'Зарплата куратору'), ('company_income', 'Доход компании'), ('company_expense', 'Расход компании')], max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('top_up', 'Пополнение'), ('deduct', 'Списание')], default='top_up', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(default='')),
                ('old_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_balance_changes_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderProfitDistribution',
        ),
        migrations.DeleteModel(
            name='ProfitDistributionSettings',
        ),
    ]
