# Generated by Django 5.1.6 on 2025-06-02 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0015_extend_balancelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdistributionsettings',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactionlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='action',
            field=models.CharField(default='legacy', max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OrderProfitDistribution',
        ),
        migrations.DeleteModel(
            name='ProfitDistributionSettings',
        ),
    ]
