# Generated by Django 5.1.6 on 2025-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0016_remove_profitdistributionsettings_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
